# Generated by Django 4.2 on 2023-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teamregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organiser',
            field=models.IntegerField(default=0),
        ),
    ]
