# Generated by Django 4.2 on 2023-04-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teamregistration'),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.games')),
            ],
            options={
                'db_table': 'game_team',
            },
        ),
    ]
