# Generated by Django 4.2 on 2023-04-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_gameteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('match_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ManyToManyField(to='game_app.games')),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.gameteam')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
